# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Efficently simulate the toy model - model0
#' @export
model0 <- function(N, M, theta) {
    .Call('_wabc_model0', PACKAGE = 'wabc', N, M, theta)
}

